parameters:

services:
    handle_create_book:
        class:     Sk9\PersonalLibrary\Domain\CommandHandlers\CreateBookCommandHandler

    command_translator:
        class:     Sk9\PersonalLibrary\Domain\CommandHandlers\CommandTranslator

    command_bus:
        class:     Sk9\PersonalLibrary\Domain\CommandHandlers\CommandBus
        arguments: ["@command_translator"]

    book_cli_command:
        class:     Sk9\PersonalLibrary\CliApplication\Commands\CreateBookCLICommand
        arguments: ["@command_bus"]
