parameters:

services:

    broadway.command_handling.simple_command_bus:
        class:     Broadway\CommandHandling\SimpleCommandBus

#    broadway.command_handling.event_dispatching_command_bus:
#        class:     Broadway\CommandHandling\EventDispatchingCommandBus
#        public: false
#        arguments: ["@broadway.command_handling.simple_command_bus", "broadway.event_dispatcher"]

    sk9.cli_app.book_command:
        class:     Sk9\PersonalLibrary\CliApplication\Commands\CreateBookCLICommand
        arguments: ["@broadway.command_handling.simple_command_bus", "@broadway.uuid.generator"]

    broadway.uuid.generator:
        class:     Broadway\UuidGenerator\Rfc4122\Version4Generator

#    broadway.event_handling.event_bus:
#        class:     Broadway\EventHandling\SimpleEventBus
#        lazy: true
#
#    broadway.event_dispatcher:
#        class:     Broadway\EventDispatcher\EventDispatcher


##tags:
##             -  { name: command_handler }
##             -  { name: broadway.domain.event_listener }
##             -  { name: broadway.event_listener }